# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2E4MDYyODNhNTVmNmQ1YmNiZTlmYjg1ZjVjMTA5YTEwYjY0NDg0NWZkZTlmM2U2M2MwMzcxNTMxODlmMGNiZDMxMzI4Zjg1OTk5YjUzNmE3MDc4M2Y4M2FjYWJjZDQ5ZmE4Nzk1NWNhM2VmNTdlY2ZmMTFjYzA3MDIxMGFhNjA=
